export { defineNuxtLaravelizeEslintConfig, eslintBaseConfig } from './presets/eslint'
export { vitestBaseConfig } from './presets/vitest'
export { tsconfigBasePath } from './presets/tsconfig'
export { oxlintBaseConfigPath } from './presets/oxlint'
export { dprintBaseConfigPath } from './presets/dprint'
export { lefthookBaseConfigPath } from './presets/lefthook'
